### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by mwallner** [nigelsim/ppmadapter#1]
please provide support for python 3.
- need to fix print in **init**.py
- following error needs to be adressed as well:

xxxxxxx:~/workspace_local/ppmadapter [master]> _ python -m ppmadapter -i hw:0 run
connect(2) call to /dev/shm/jack-0/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Using input: HDA Intel PCH: ALC887-VD Alt Analog (hw:0,2)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/trunk/workspace/ppmadapter/ppmadapter/__main__.py", line 5, in <module>
    sys.exit(ppmadapter.main())
  File "/trunk/workspace/ppmadapter/ppmadapter/**init**.py", line 205, in main
    with PPMDecoder(rate) as ppm:
  File "/trunk/workspace/ppmadapter/ppmadapter/**init**.py", line 75, in **init**
    ecodes.EV_KEY: {288: 'BTN_JOYSTICK'}
  File "/usr/lib/python3.5/site-packages/evdev/uinput.py", line 107, in **init**
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
SystemError: Objects/longobject.c:403: bad argument to internal function

**Comment by capoei** [comment]
does this still work for you?
